### ISSUE TITLE
Custom action in list or thumbnail views

### ISSUE THREAD

**Issue by davidromani** [artgris/FileManagerBundle#109]
It is possible to extend custom actions? I need to open modal with an audio player for mp3 uploaded files.

I've read the documentation but nothing refers to this topic. Thanks for your help.

**Comment by artgris** [comment]
Hello, it's not possible. You need to [override my bundle](https://symfony.com/doc/current/bundles/override.html)

**Comment by davidromani** [comment]
@artgris thank you so much for answering
