### ISSUE TITLE
Remove the dependency on Sensio/framework-extra-bundle

### ISSUE THREAD

**Issue by Ishadijcks** [artgris/FileManagerBundle#113]
`Sensio/framework-extra-bundle` is deprecated: https://github.com/sensiolabs/SensioFrameworkExtraBundle

Could it be removed as a dependency? It does not appear it is actually used anywhere
https://github.com/artgris/FileManagerBundle/search?q=Sensio

**Comment by czachor** [comment]
I had to add the package `doctrine/annotations` ^1.14. Anyway since v2.0, the `AnnotationRegistry::registerLoader` method is removed and since 1.8 deprecated.
The package `symfony/framework-bundle` is also required.
