### ISSUE TITLE
How to integrate the FileManagerBundle to symfony 4?

### ISSUE THREAD

**Issue by DanielInk** [artgris/FileManagerBundle#12]
Hi i am trying to use your file manager with symfony 4 but i can’t find the files that you specified in the documentation obviously because the structure changed even though i tried to set the equivalent by adding the next block of code into **services.yml**  

```
    Artgris\Bundle\FileManagerBundle\Helpers\FileManager:
        arguments:
            $webDir: '%upload_directory%'
```

and this one on **routes.yml**

```
  artgris_bundle_file_manager:
       path: /manager
       controller: Artgris\Bundle\FileManagerBundle\Controller\ManagerController::indexAction
```

but it throws and error: Please define a conf parameter in your route, can you give  me a little support on this please?

**Comment by dimachen** [comment]
Hi.

You need to create file 

config/packages/artgris_file_manager.yaml

and copy/paste configuration there.

**Comment by antoine1003** [comment]
Also make sure to reach this url : `/manager/?conf=default` with conf parameter set !

**Comment by jimiero** [comment]
@antoine1003 i'm having the same issue, in dev mode it works, in production mode it throws this error:

"Please define a conf parameter in your route"

Any idea what's wrong?

I have config file in 

config/packages/artgris_file_manager.yaml

and also tried placing on:

config/packages/prod/artgris_file_manager.yaml

same error
