### ISSUE TITLE
Symfony 6.3

### ISSUE THREAD

**Issue by pfpro** [artgris/FileManagerBundle#126]
Hi there,

i try to upgrade from symfony 6.2 to 6.3 and get the following log:

`Method "Symfony\Component\DependencyInjection\Extension\ExtensionInterface::load()" might add "void" as a native return type declaration in the future. Do the same in implementation "Artgris\Bundle\FileManagerBundle\DependencyInjection\ArtgrisFileManagerExtension" now to avoid errors or add an explicit @return annotation to suppress this message.`

Any chance you can fix this?

Best regards

**Comment by john-dufrene-dev** [comment]
@pfpro I create a pull request to fix this issue : https://github.com/artgris/FileManagerBundle/pull/128
Waiting for merge it

**Comment by pfpro** [comment]
thx a lot, you are appreciated!

**Comment by pfpro** [comment]
i might found another issue, after uploading a file:

{"exception":"[object] (ErrorException(code: 0): Deprecated: basename(): Passing null to parameter #2 ($suffix) of type string is deprecated at /homepages/42/d121516004/htdocs/wwwroot_v3/r6/vendor/artgris/filemanager-bundle/Helpers/UploadHandler.php:1481)"} []
