### ISSUE TITLE
Position flash messages

### ISSUE THREAD

**Issue by pfpro** [artgris/FileManagerBundle#129]
Hello, would it be optionally possible to place the flash messages at the top of the page instead of at the bottom?

**Comment by xDeSwa** [comment]
copy 'vendor\artgris\filemanager-bundle\Resources\views\manager.html.twig' to 'templates\bundles\ArtgrisFilemanagerBundle\manager.html.twig' 

you can modify how you want.
you can do override main template with this method

**Comment by elliotlgnetesting** [comment]
i did copy the  'vendor\artgris\filemanager-bundle\Resources\views\manager.html.twig' to templates\bundles\ArtgrisFilemanagerBundle\manager.html.twig

but it doesn't works, i mean it still referring to the 'vendor\artgris\....
Maybe you can help me ?

**Comment by xDeSwa** [comment]
root/templates/bundles/ArtgrisFileManagerBundle/manager.html.twig

i tested just now, its work.

**Comment by elliotlgnetesting** [comment]
but I've already done that ?: 
/var/www/Project/vendor/artgris/filemanager-bundle/Resources/views/manager.html.twig to 
/var/www/Project/templates/bundles/ArtgrisFilemanagerBundle/manager.html.twig

I'm sorry but it still doesn't works :(

**Comment by xDeSwa** [comment]
büyük harf veya küçük harf windows da çok önemsenmiyor ama unixde öyle değil. tebrikler
