### ISSUE TITLE
Change the translation

### ISSUE THREAD

**Issue by elliotlgn** [artgris/FileManagerBundle#136]
Hello, i'd like to change the translation english to french, how can i do that ? 
Thanks !

**Comment by xDeSwa** [comment]
symfony dilini fr olarak ayarladığınızı varsayıyorum
open folder 'ArtgrisFileManagerBundle' in root/translations. then create messages.fr.yml file or copy original file to here

like this
**root/translations/ArtgrisFileManagerBundle/messages.fr.yml**

**Comment by elliotlgnetesting** [comment]
First thanks a lot for you answer ! 

But it doesn't work if I do : 
/var/www/Project/translations/ArtgrisFileManagerBundle/messages.fr.yml

I don't need to change a configuration to use message.fr.yml instead of message.en.yml ?

I mean directly into the  vendor ?

**Comment by xDeSwa** [comment]
bundle already has fr.yml in vendor/artgris/filemanager-bundle/Resources/translations/messages.fr.yml

you want override?

**Comment by elliotlgnetesting** [comment]
No i don't, i just want to use it

**Comment by xDeSwa** [comment]
parameters:
    locale: 'fr'
in
config/services.yaml

**Comment by elliotlgnetesting** [comment]
doesn't work
i've never use translation before, maybe i have to change something first ?

**Comment by xDeSwa** [comment]
if you didnt install translation bundle before;

**`composer require symfony/translation`**

**Comment by elliotlgnetesting** [comment]
i've already installed it

**Comment by xDeSwa** [comment]
check config/packages/translations.yaml

framework:
    default_locale: '%locale%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en

**Comment by elliotlgnetesting** [comment]
Yess thanks a lot !
