### ISSUE TITLE
How can i make the uploaded files override the existing ones that have the same name.

### ISSUE THREAD

**Issue by mramine364** [artgris/FileManagerBundle#17]
Hi,
i want to upload files using the bundle artgris/FileManagerBundle
and i want the uploaded files override the existing ones that have the same name.

Thank you for your help.

**Comment by mramine364** [comment]
I figured out this problem,
by overiding the method 'get_file_name' in the class 'Artgris\Bundle\FileManagerBundle\Helpers\UploadHandler'

**Comment by chiqui3d** [comment]
Do you have an example of how to apply your own upload handler?

**Comment by chiqui3d** [comment]
Well although it could also be solved by creating event subscribers before and after the UPLOAD,
