### ISSUE TITLE
Browser Bug

### ISSUE THREAD

**Issue by DZander** [artgris/FileManagerBundle#19]
Button "Add files" does not work unter Firefox and Internet Explorer.

Symfony 3.4.14
artgris/FileManagerBundle 1.3.2
Firefox ESR 52.9.0 and Firefox Quantum 61.0.2 and also Internet Explorer 11.
Google Chrome ist working fine.

**Comment by DZander** [comment]
Found out the problem.
.fileinput-button in manager.html.twig have to be a span, not button.

**Comment by DZander** [comment]
<span class="btn btn-success btn-sm fileinput-button">
            <i class="glyphicon glyphicon-file"></i>
            <span>{{ 'button.add.files'|trans }}</span>
            <input id="fileupload" type="file"
                   data-url="{{ path('file_manager_upload', fileManager.queryParameters) }}"
                   name="files[]" multiple=""
                   accept="{{ fileManager.configuration.accept is defined ? fileManager.configuration.accept : (fileManager.type ? accept(fileManager.type)) }}">
        </span>

**Comment by artgris** [comment]
Thx @DZander
