### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Azariil** [artgris/FileManagerBundle#2]
Hi. I'm trying to install a bundle, but in return I get an error:

>   [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]   
>   Invalid key "router" found in arguments of method "__construct()" for servi  
>   ce "file_type_service": only integer or $named arguments are allowed.   

when executing the command:

> ./bin/console assets:install --symlink

I use Symphony 3.3.10 and PPP 7.0.15
Help please understand what the problem is.
Thanks

**Comment by artgris** [comment]
Hi, I cannot reproduce your bug, i'm testing with a 'symfony new project 3.3.10' and I don't have any problems. Have you more detail about bug/symfony conf ? or better, can you shared me a github project where i can reproduce bug.

**Comment by Azariil** [comment]
Unfortunately I can not put out a working project. But. I tried to put the bandle on a clean Sympfony. But the mistake remains. I tried to do this on a server with Linux and PHP 7.1. I tried to do it on a computer with Windows and three different versions of PHP: 5.6, 7.0 and 7.1, but the result is the same.

>   [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]
>   Invalid key "router" found in arguments of method "__construct()" for service "file
>   _type_service": only integer or $named arguments are allowed.

If there is a need, I can put the project on the github, but there's only Symofny and bundle. I installed everything with a composer.

**Comment by Azariil** [comment]
Just in case, added the code to the repository. There's only Symfony and bandle.
https://github.com/Azariil/test-symfony
After adding routing, I can not even run the command:
php bin/console server:run
The same error is displayed:

>   [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]
>   Invalid key "router" found in arguments of method "__construct()" for service "file
>   _type_service": only integer or $named arguments are allowed.

**Comment by artgris** [comment]
Hi, Thx, i could reproduce your problem  :+1: , and after several tests, all works after i removed these lines from your composer.json (and run a composer update) :
        "platform": {
            "php": "5.5.9"
        },
or you can replace 5.5.9 by 5.6 and everything is still working. I will increase the bundle php min version. 

Please lets me know if you still have problem

**Comment by artgris** [comment]
My bundle has already  "php": ">=5.6.0" in composer.json, this must come from "plaform", he created a fake platform packages always with a php 5.5.9 ... 
Strange that composer not indicate that the bundle is not compatible with the "plaform" configuration ...

**Comment by Azariil** [comment]
Thank you! Everything works fine.

**Comment by artgris** [comment]
ok i understood ... it's due to my 1.0.10 version, with line: "php": "^5.3.9 || ^7.0" ... because it's the only  compatible version with "php": "5.5.9", Composer try to install 1.0.10 but it was not compatible with 5.5.9. My bad

**Comment by PronayMallick** [comment]
I have encountered the same problem.. and still does not work by replacing 5.5.9 by 5.6.. any help?
