### ISSUE TITLE
Renaming versions

### ISSUE THREAD

**Issue by david-cefr** [artgris/FileManagerBundle#24]
Hi, 
Nice work !
I found an issue while testing your bundle. When you configure "upload > image_versions", renaming action will only rename the original.

Edit : in order to remove deprecation warning, you have to update the route annotation to : 
`use Symfony\Component\Routing\Annotation\Route`

**Comment by artgris** [comment]
Hi, it's normal behavior, the edition is restricted to the edited file (as the deletion)
