### ISSUE TITLE
SF4 TinyMCE v5

### ISSUE THREAD

**Issue by ArnaudDoubremelle** [artgris/FileManagerBundle#39]
Hello, i use fileManagerBundle 1.4 with TinyMCE v5. When I insert an image, the modal opens and when I select the image I want, nothing happens and I get the error

`manager.js:164 Uncaught TypeError: top.tinymce.activeEditor.windowManager.getParams is not a function
    at HTMLTableCellElement.<anonymous> (manager.js:164)
    at HTMLFormElement.dispatch (jquery.min.js:3)
    at HTMLFormElement.q.handle (jquery.min.js:3)`

Sorry for my English, Thanks

**Comment by artgris** [comment]
Hi, TinyMCE v5 required fileManagerBundle > 1.4.2, try composer update artgris/filemanager-bundle

**Comment by ArnaudDoubremelle** [comment]
Composer.json
`"artgris/filemanager-bundle": "^1.4.2",`
composer update artgris/filemanager-bundle
`Installing artgris/filemanager-bundle (1.4.3): Downloading (100%)`
But i always have the same error with the same manager.js

**Comment by artgris** [comment]
always line 164 ? (your web assets are up to date ?)

**Comment by ArnaudDoubremelle** [comment]
When i go in vendor>artgris>filemanager-bundle>Resources>public>js>manager.js
line 164 ` var args = top.tinymce.activeEditor.windowManager.getParams();`

**Comment by artgris** [comment]
I forgot to create a new release, plz wait a few minutes and run composer update artgris/filemanager-bundle , new version 1.4.4 should fix your problem.

sorry.

**Comment by ArnaudDoubremelle** [comment]
Thanks !
