### ISSUE TITLE
Hide folders from user

### ISSUE THREAD

**Issue by 71m024** [artgris/FileManagerBundle#43]
Is there a possible way to hide  folders from specific users?  
We have a hierarchy which contains folders for every user. If a user tries to access a foreign folder a AccessDeniedException is thrown but we would like to hide all the folders, not owned by a user.  
A hook for access-checks or something similar would be useful.

**Comment by akerbel** [comment]
I have some kind the same. I created my custom config service and provided different 'dir' parameter for different users. The user cannot go outside of his folder and as result cannot see folders of other users.
