### ISSUE TITLE
Maximum function nesting level of '256' reached, aborting!

### ISSUE THREAD

**Issue by shades3002** [artgris/FileManagerBundle#45]
### error when trying to understand the template for its adaptation:

`templates/bundles/ArtgrisFileManagerBundle/manager.html.twig`

manager.html.twig ->
`{% extends "@ArtgrisFileManager/manager.html.twig" %}`

error:
`Maximum function nesting level of '256' reached, aborting!`

**Comment by artgris** [comment]
Hi, 

try {% extends "@!ArtgrisFileManager/manager.html.twig" %} to prevent circulare reference
