### ISSUE TITLE
IE compatibility

### ISSUE THREAD

**Issue by Kaaly** [artgris/FileManagerBundle#48]
Hi,

i use your bundle on project with ckeditor module but it seems to be not compatible with Internet Explorer.

In manager.js file, the line below doesn't work : 
`var url = new URL(window.location.href);`

IE does not support URL

**Comment by WouterCypers** [comment]
@artgris I have fixed this (tested on IE11). Is there a way I can contribute to the project or do I just post the code here?

**Comment by artgris** [comment]
Hi @WouterCypers, you can create a pull request. Thx for your contribution :+1:

**Comment by WouterCypers** [comment]
@artgris I created a PR (#49)
