### ISSUE TITLE
Client side crop image

### ISSUE THREAD

**Issue by ArnaudDoubremelle** [artgris/FileManagerBundle#51]
Hello, on the readme in the feature i see "File Upload widget used : blueimp/jQuery-File-Upload" with "Client-side image resizing/crop" but when i edit a file to the filemanager i dont have this interface
https://blueimp.github.io/jQuery-File-Upload/ . Is it possible to have it ?

**Comment by artgris** [comment]
Hi @ArnaudDoubremelle,

This feature is not integrated (it's an error in the readme), but I guess it's possible by overriding the bundle templates (manager.html.twig):
https://symfony.com/doc/current/bundles/override.html#templates

But, If you need to resize an image, you can do this in the configuration:

    conf:
        default:
            dir: "../public/uploads/"
            type: image
            upload:
                image_versions: {'': {max_width: 100, max_height: 100}}


or crop an image:

    conf:
        default:
            dir: "../public/uploads/"
            type: image
            upload:
                image_versions: {'': {crop: true, max_width: 10, max_height: 10}}
