### ISSUE TITLE
Embedded version ?

### ISSUE THREAD

**Issue by gobolabs** [artgris/FileManagerBundle#53]
Hello,

First, thanks for the work! 

 i found a "workaround" (frame) to embed the file manager into a twig template after a few try of overrides.

Do I missed something or there is a "simple" way to embed the file manager into a view ?

If not, could it be possible ? A reason to avoid it ?

Regards,

**Comment by artgris** [comment]
Hi @gobolabs,
Thx =)
To embed the file manager you can use an iframe or override the bundle templates (manager.html.twig):
https://symfony.com/doc/current/bundles/override.html#templates

**Comment by gobolabs** [comment]
Hello, thanks for answer.

Ok for the iframe. It works but not as a "normal" template, naturally. 

We have try to override the manager.html.twig but without success. Stop me if I am wrong, but we have to override the controllers also, etc... 

And after few test, there are too much depedencied atm to "just" be able to override the only template... Do I am right ?

**Comment by artgris** [comment]
Why you need to override the controller ?

you must override the view by managing integration conflicts (In your case, it seems complicated...) between filemanager and your template (js and css) no link with the controller

**Comment by gobolabs** [comment]
Yeah, that's the points. Pretty complicated to juste override the view + override the front ... but I will try again asap. I'll keep you in touch. 

Thanks for the answers ! 

Regards,
