### ISSUE TITLE
Link names

### ISSUE THREAD

**Issue by vojtechadam** [artgris/FileManagerBundle#55]
I would like to use the names of the files (per row, listed as list) also as links. Using links (<a href= ...) around them, instead of always clicking on the download button. Also my Table rows are not clickable, using the custom configuration. Any ideas for me? Thank you

**Comment by artgris** [comment]
Hi @vojtechadam , sorry for my late reply.

you can override the twig view (_list.html.twig and _thumbnail.html.twig), but beware, the click is used in WYSIWYG integration to select a file, so it may not be compatible
