### ISSUE TITLE
Notice: Undefined property: stdClass::$url

### ISSUE THREAD

**Issue by kaistaerk** [artgris/FileManagerBundle#56]
Hi there,

Iam using Symfony 4.2 and just installed the file manager. There was a problem in the ManagerController, so i got the error

`Notice: Undefined property: stdClass::$url`

I took a look on it.

ManagerController:277
`$file->url = $this->generateUrl('file_manager_file', array_merge($fileManager->getQueryParameters(), ['fileName' => $file->url]));`

After dumping $file, i changed it to $file->name and it works.

Is there any reason for using "url" or did I found a bug?

Kind regards
Kai

**Comment by kaistaerk** [comment]
it occurs only in a local env.....

**Comment by artgris** [comment]
Hi @kaistaerk , sorry for my late reply.

Yes you found a bug, but changed '$file->name' is not the solution. I will correct this in my latest version.

Thx =)
