### ISSUE TITLE
Progressbar when uploading

### ISSUE THREAD

**Issue by Dave268** [artgris/FileManagerBundle#59]
Hello,
Your filemanagerbundle was exactly what I needed. I would have one suggestion/question though; would it be possible to display a progressbar when files are being uploaded? This would be really helpfull to see what is happening for the user. Thanks a lot for the great work.

**Comment by artgris** [comment]
Hi @Dave268 , I just created a new release (1.6) with a progress bar (at the top of the page like a single-page app)

**Comment by Dave268** [comment]
Thanks a lot, I'm gone check that out :)

**Comment by Dave268** [comment]
I like it :) It's actually a really elegant way to do show that progressbar :) Thanks a lot
