### ISSUE TITLE
Return multiple folder

### ISSUE THREAD

**Issue by Mysh3ll** [artgris/FileManagerBundle#6]
Hello, 

First of all congratulations for your work.
I would like to know how to return multiple directories from a service.

Indeed, following your documentation I managed to create a service that returns an array with the target directory (like this):

`return [
                'dir' => '../web/uploads/super_admin'
            ];`

But, in my case, i would like to return multiple directories (like this):

`return [
                'dir' => ['../web/uploads/super_admin', '../web/uploads/admin']
            ];`

Like this, the user can access multiple folders at the same time.
Because some directories are not nested with each other!

Could you give me an answer?

**Comment by artgris** [comment]
Hi @Mysh3ll  and Thx u, 

This is not possible and would create several problems (folder choice when we upload a file, same file name in multiple folder ...).

Could you just put uploads in 'dir' ? : 

`return [ 'dir' => '../web/uploads' ];` 
 
or maybe create a new directorie in web, for example /web/mergedDirectories
and put in mergedDirectories 2 symlinks for `super_admin`  and `admin`, that could work ...
