### ISSUE TITLE
RecursiveDirectoryIterator

### ISSUE THREAD

**Issue by devcut** [artgris/FileManagerBundle#62]
Hello @artgris, 

I have an error in my project with your Bundle :

<img width="797" alt="Capture d’écran 2020-03-24 à 14 21 36" src="https://user-images.githubusercontent.com/12175420/77430458-88496c00-6ddb-11ea-8b37-be36bc2be0bf.png">

I have the same files and folder as in production but in production it's working.

Any ideas ?

Thanks

**Comment by artgris** [comment]
Hi, maybe a permission issue on your production files|directories ...
