### ISSUE TITLE
AWS S3 support

### ISSUE THREAD

**Issue by vincentcox** [artgris/FileManagerBundle#77]
Hello Artgris,

I was wondering if it is possible to get this working with S3 buckets. Currently it saves everything locally.

I was thinking if I would replace every file_put_contents (or fopen) function to an aws upload function would that do the trick? Or will the application break most likely?

<img width="1417" alt="Screenshot 2020-10-29 at 14 56 14" src="https://user-images.githubusercontent.com/9286611/97583203-f51e8780-19f6-11eb-845a-43c40e69b648.png">

**Comment by artgris** [comment]
I don't know I don't use S3 buckets. Give it a try
