### ISSUE TITLE
Installation : Please define a "dir" or a "service" parameter in your config.yml

### ISSUE THREAD

**Issue by louan-dubois** [artgris/FileManagerBundle#81]
Hi,
I'm just trying to install the bundle, and after following the installation steps, I get this error : 
`Please define a "dir" or a "service" parameter in your config.yml.`
I've checked and re-checked every `yml` file, tried to add an other conf, a service, but I don't get it. I must have missed something somewhere. My files are a little bit different though, as `routing.yml` in the readme is `routes.yml` for me, maybe it could come from there.
Below my different versions :
```
$ php -v 
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

$ composer -V
Composer version 2.0.9

$ symfony -V
Symfony CLI version v4.23.2 (2021-03-02T17:16:03+0000 - stable)
```
I've found this issue https://github.com/artgris/MediaBundle/issues/51 which seems similar, but since it's not the same bundle, files are different, and I don't know how to get the "Debug" line.
If you need any more info, let me know and I'll upload it.
Thanks for your help!

**Comment by rtfjr86** [comment]
Did you see this in the README?

`# app/config/config.yml
artgris_file_manager:
    conf:
        default:
            dir: "../public/uploads"`

It doesn't have to be called config.yml either. I have mine named `artgris_file_manager.yaml` in the `config/packages` dir.

**Comment by louan-dubois** [comment]
Thank you for your quick reply !
I didn't know that the name and location could change, I thought there were mandatory. I put my `config.yaml` in `myApp/config/config.yml`, and now following your advise it works. 
Thank you
