### ISSUE TITLE
unable to load js and css

### ISSUE THREAD

**Issue by kaizer666** [artgris/FileManagerBundle#83]
php - 7.4.14
composer - 2.0.2
Symfony - 5.1.11
I installed this bundle via composer as per the README.
Registered all configuration files
As a result, when I try to go to the page /manager/?conf=default - css and js are not loaded, they are loaded as a simple page, and not as files.

http://joxi.ru/BA0b8yuMbxbkmy
http://joxi.ru/MAjegvijgNgQ2e

**Comment by artgris** [comment]
Hi, @kaizer666, try this plz:

`php bin/console assets:install --symlink`

**Comment by kaizer666** [comment]
@artgris thank you! It's work!
