### ISSUE TITLE
Please define a "dir" or a "service" parameter in your config.yml

### ISSUE THREAD

**Issue by langziyang** [artgris/FileManagerBundle#89]
i am use symfony 5+
tinymce 5+

i follow the demo
created config/routes/artgris_file_manager.yaml and config/packages/artgris_file_manager.yaml
copy demo yaml file content

whe i open file manager i get the error:   Please define a "dir" or a "service" parameter in your config.yml

**Comment by Psycomentis06** [comment]
Did you find a way to solve this?
