### ISSUE TITLE
Symfony 6 compatibility

### ISSUE THREAD

**Issue by NodokaMurmevent** [artgris/FileManagerBundle#92]
Hello, did you have any plan for symfony 6 ?

**Comment by artgris** [comment]
Hi @NodokaMurmevent, I have no plan and I wonder if it is relevant to continue this bundle. Everything has to be redone... (use modern js, update blueimp/jQuery-File-Upload, allow remote server ...)

**Comment by NodokaMurmevent** [comment]
ho ok. i‘s sad, but i totally understand, it‘s true the jquery part is not easy to work with.
I guess it's the same for MediaBundle ?

I will need to find things for replace everything so. 

Thanks for all the work previously do !

**Comment by artgris** [comment]
@Arkounay created a more modern version of the media bundle https://github.com/Arkounay/ux-media so I might try to remake my bundle, but it will take some time.

**Comment by miguelgilmartinez** [comment]
It's a great bundle, with no competitors alike AFAIK.

**Comment by artgris** [comment]
#93
